version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - cd: /service/
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
      - cd: /service/
      - mvn package
artifacts:
  files:
    - service/target/drdolittle-petclinic-1.5.2.war
    - appspec.yml
    - codedeploy/*
discard-paths: yes
